### PR TITLE
bump version to 24.35.30872.24-1018

### PR DESCRIPTION
**Pull request by androniychuk**
remove intel-igc-cm as dependency

add DEB_BUILD_MAINT_OPTIONS = hardening=+all

### CODE REVIEW

**Comment by androniychuk** [comment]
there....

**Comment by androniychuk** [comment]
1 thing... how is the ocloc.alternatives and both the ocloc.postinst script supposed to work?

**Comment by androniychuk** [comment]
I removed the .postinst and .prerm for ocloc
and set the priority to the major minor of the component versions for update alternatives

**Comment by mckees** [comment]
Ya, I think that may have been Timo's response to seeing the way that postinstall script was handling things. LGTM

**Pull request merged**
